---
title: "Project analysis"
author: "Yichi Zhang"
date: "2023-04-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(lavaan)
library(dplyr)
library(modelsummary)
library(matlib)
library(dplyr)
library(foreach)
library(DetMCD)
library(sirt)
source("analysis/functions_class.R")
source("analysis/Rallfun-v39")
```

```{r}
## raw dataset
data("HolzingerSwineford1939")
data <- HolzingerSwineford1939[157:301, -c(1:6)]
rownames(data) <- 1:nrow(data)
datasummary_skim(data)
```


```{r}
# CFA
path <- '
f1 =~ x1 + x2 + x3
f2 =~ x4 + x5 + x6
f3 =~ x7 + x8 + x9
'
model <- cfa(path, data = data, estimator = "MLM")
summary(model, fit.measures = TRUE)
resid <- resid(model)
```

```{r}
## builtin function from lavaan to extract lambda matrix
Lambda <- lavaan::inspect(model, what = "est")$lambda
## extract factor variance covariance matrix directly
Phi <- lavaan::inspect(model, what = "est")$psi
```

```{r}
# ## focus on one factor first
mod1 <- 'f1 =~ x1 + x2 + x3'
## add sex as a grouping variable
data_gp <- cbind(data, "sex" = HolzingerSwineford1939[157:301,]$sex)
## fit a one factor cfa model
fit_dat1 <- cfa(mod1, data = data_gp,
                group = "sex",
                estimator = "MLM",
                std.lv = TRUE)
summary(fit_dat1, fit.measures = TRUE)
## original data
res1 <- alignment(fit_dat1, group_name = c("female", "male"))
```

Here is the second dataset with good leverage points. 

```{r}
# Data set 2 -- Good leverage points
h = c(0.3881, 1.3762, 5.6153, 2.4312, 1.7442)
bartlett_predict <- lavPredict(model, method = "Bartlett")

data2_new_ob <- foreach(i = 141:145, j = 1:5) %do%{
  data[i, ] + h[[j]]*Lambda%*%bartlett_predict[i, ]
}

data2_new_ob <-data.frame(t(sapply(data2_new_ob,c)))

#replace the last 5 observations and the whole data set 2 is:
data2 <- rbind(data, data2_new_ob)
data2 <- data2[-(141:145), ]
rownames(data2) <- 1:nrow(data2)
data2 <- data.frame(matrix(unlist(data2), ncol=length(data2), byrow=FALSE))
data2 <- cbind(data2, "sex" = HolzingerSwineford1939[157:301,]$sex)
data2_fe <- data2 %>% filter(sex == 1)
data2_ma <- data2 %>% filter(sex == 2)
```

## mve

<!-- ```{r, include = FALSE} -->
<!-- mean_rob_ma <- mve_mahalanobis(x = data2_ma[,1:3])$weighted.mean -->
<!-- cov_rob_ma <- mve_mahalanobis(x = data2_ma[,1:3])$weighted.covariance -->
<!-- mean_rob_fe <- mve_mahalanobis(x = data2_fe[,1:3])$weighted.mean -->
<!-- cov_rob_fe <- mve_mahalanobis(x = data2_fe[,1:3])$weighted.covariance -->
<!-- mod2 <- "f1 =~ V1 + V2 + V3" -->
<!-- fit_dat2_ma <- cfa(mod2, -->
<!--                 sample.cov = cov_rob_ma, -->
<!--                 sample.mean = mean_rob_ma, -->
<!--                 sample.nobs = nrow(data2_ma), -->
<!--                 std.lv = TRUE) -->
<!-- summary(fit_dat2_ma, fit.measures = TRUE) -->
<!-- coef(fit_dat2_ma) -->
<!-- fit_dat2_fe <- cfa(mod2, -->
<!--                 sample.cov = cov_rob_fe, -->
<!--                 sample.mean = mean_rob_fe, -->
<!--                 sample.nobs = nrow(data2_fe), -->
<!--                 std.lv = TRUE) -->
<!-- summary(fit_dat2_fe, fit.measures = TRUE) -->
<!-- coef(fit_dat2_fe) -->
<!-- ld <- rbind(t(lavInspect(fit_dat2_ma, what = "est")$lambda), -->
<!--             t(lavInspect(fit_dat2_fe, what = "est")$lambda)) -->
<!-- rownames(ld) <- c("male", "female") -->
<!-- nu <-  rbind(t(lavInspect(fit_dat2_ma, what = "est")$nu), -->
<!--             t(lavInspect(fit_dat2_fe, what = "est")$nu)) -->
<!-- rownames(nu) <- c("male", "female") -->
<!-- res2 <- invariance.alignment( -->
<!--         lambda = ld, -->
<!--         nu = nu, -->
<!--         wgt = matrix(sqrt(c(nrow(data2_ma), nrow(data2_fe))), nrow = 2, ncol = 3) -->
<!--     ) -->
```{r}
res_mve <- robalign(method = "mve_mah", data_g1 = data2_fe[,1:3], data_g2 = data2_ma[,1:3],
                    mod = mod2, group_name = c("female", "male"))
```

## mcd

```{r}
res_mcd <- robalign(method = "mcd_mah", data_g1 = data2_fe[,1:3], data_g2 = data2_ma[,1:3],
                    mod = mod2, group_name = c("female", "male"))
# mean_rob_mcd <- mcd_mahalanobis(data2[,1:3])$weighted.mean
# cov_rob_mcd <- mcd_mahalanobis(data2[,1:3])$weighted.covariance
# fit_dat3 <- cfa(mod2,
#                 sample.cov = cov_rob_mcd,
#                 sample.mean = mean_rob_mcd,
#                 sample.nobs = 145,
#                 group = "sex",
#                 std.lv = TRUE)
# coef(fit_dat3)
# res3 <- alignment(fit_dat3)
```

## projection mve

```{r}
res_pro_mve <- robalign(method = "pro_mve", data_g1 = data2_fe[,1:3], data_g2 = data2_ma[,1:3],
                    mod = mod2, group_name = c("female", "male"))
# mean_rob_pmve <- projection_mve(x = data2[,1:3])$weighted.mean
# cov_rob_pmve <- projection_mve(data2[,1:3])$weighted.covariance
# fit_dat4 <- cfa(mod2,
#                 data = data2,
#                 sample.cov = cov_rob_pmve,
#                 sample.mean = mean_rob_pmve,
#                 sample.nobs = 145,
#                 group = "sex",
#                 std.lv = TRUE)
# # summary(fit_dat2, fit.measures = TRUE)
# res4 <- alignment(fit_dat4)
```

## projection mcd

```{r}
res_pro_mcd <- robalign(method = "pro_mcd", data_g1 = data2_fe[,1:3], data_g2 = data2_ma[,1:3],
                    mod = mod2, group_name = c("female", "male"))
# mean_rob_pmcd <- projection_mcd(x = data2[,1:9])$weighted.mean
# cov_rob_pmcd <- projection_mcd(data2[,1:9])$weighted.covariance
# fit_dat5 <- cfa(mod2,
#                 data = data2,
#                 sample.cov = cov_rob_pmcd,
#                 sample.mean = mean_rob_pmcd,
#                 sample.nobs = 145,
#                 group = "sex",
#                 std.lv = TRUE)
# # summary(fit_dat2, fit.measures = TRUE)
# res5 <- alignment(fit_dat5)
```

## outpro mve

```{r}
res_outmve <- robalign(method = "outpro_mve", data_g1 = data2_fe[,1:3], data_g2 = data2_ma[,1:3], mod = mod2, group_name = c("female", "male"))
# mean_rob_omve <- outpro_mcd(data2[,1:9])$weighted.mean
# cov_rob_omve <- outpro_mcd(data2[,1:9])$weighted.covariance
# fit_dat6 <- cfa(mod2,
#                 data = data2,
#                 sample.cov = cov_rob_omve,
#                 sample.mean = mean_rob_omve,
#                 sample.nobs = 145,
#                 group = "sex",
#                 std.lv = TRUE)
# # summary(fit_dat2, fit.measures = TRUE)
# res6 <- alignment(fit_dat6)
```

## outpro mcd

```{r}
res_outmcd <- robalign(method = "outpro_mcd", data_g1 = data2_fe[,1:3], data_g2 = data2_ma[,1:3], mod = mod2, group_name = c("female", "male"))
# mean_rob_omcd <- outpro_mve(data2[,1:9])$weighted.mean
# cov_rob_omcd <- outpro_mve(data2[,1:9])$weighted.covariance
# fit_dat7 <- cfa(mod2,
#                 data = data2,
#                 sample.cov = cov_rob_omcd,
#                 sample.mean = mean_rob_omcd,
#                 sample.nobs = 145,
#                 group = "sex",
#                 std.lv = TRUE)
# # summary(fit_dat2, fit.measures = TRUE)
# res7 <- alignment(fit_dat7)
```

## comparison

```{r}
## factor means and variances
list(res1$pars,
    res_mve$align_res$pars, res_mcd$align_res$pars,
    res_pro_mve$align_res$pars, res_pro_mcd$align_res$pars,
    res_outmve$align_res$pars, res_outmcd$align_res$pars)
# ## factor loadings
list(res1$lambda.aligned, 
     res_mve$align_res$lambda.aligned, res_mcd$align_res$lambda.aligned,
     res_pro_mve$align_res$lambda.aligned, res_pro_mcd$align_res$lambda.aligned,
     res_outmve$align_res$lambda.aligned, res_outmcd$align_res$lambda.aligned)
## factor intercepts
list(res1$nu.aligned, 
     res_mve$align_res$nu.aligned, res_mcd$align_res$nu.aligned,
     res_pro_mve$align_res$nu.aligned, res_pro_mcd$align_res$nu.aligned,
     res_outmve$align_res$nu.aligned, res_outmcd$align_res$nu.aligned)
```

<!-- ## reliability -->

## covariance matrix

```{r}
cov(data_gp[1:3])
res_outmve$rob_est_g1$weighted.covariance
res_outmve$rob_est_g2$weighted.covariance
(res_outmve$rob_est_g1$weighted.covariance + res_outmve$rob_est_g2$weighted.covariance)/2
```

