---
title: "Prospectus"
author: "Yichi, Lai"
bibliography: references.bib
format: pdf
---

## Background

Educational or psychological researchers are often interested in assessing people's latent traits that are not directly observable (i.e., self-efficacy). One commonly used assessment method is to develop psychological scales and ask people to rate the scale items. However, an important assumption of using psychological scales is measurement invariance (MI), meaning the scales have the same measurement properties for people from different groups. By establishing MI, researchers could compare latent means across groups while holding measurement parameters invariant. However, exact invariance (i.e., absolute equivalence in parameter estimates) is often rejected in applied research, so the alignment optimization has been proposed to accurately estimate the latent trait means without requiring the exact invariance across groups [@asparouhov2014]. 

<!-- Specifically, alignment automates the MI analysis by minimizing a loss function that captures the amount of measurement noninvariance across items and groups -->

However, alignment is based on multiple-group confirmatory factor analysis (MG-CFA), in which the variance-covariance matrix and correlations are involved for the calculation of such procedure. It is well-known that the traditional measures of scatter matrix and covariance are sensitive to outliers or data contamination. The breakdown point of the sample covariance matrix is only 1/n [@wilcox2017modern]. That is, even a single outlier can substantially alter the values of estimates. In multivariate analyses such as CFA, defining, identifying and categorizing data contamination are nontrivial. Given the nature of CFA - parallel to regression, data contamination can be classified into three general categories: leverage points (good and bad), outliers and influential points. Influential points will be the focus for our current project since their inclusion/exclusion will have a great impact on the assessment of the model fit [@yuan20088]. 

## The Current Study

We will develop a robust alignment optimization (RAO) that could produce consistent and efficient estimation with the existence of outliers or influential observations. 

### Paper or Presentation

The results of this study will be shared with class in presentation.

## Method

1.  robust covariance matrix (Lai)

The second step is to apply the alignment optimization on the obtained robust covariance matrix. This could be achieved by first fitting a confirmatory factor analysis (CFA) model using the robust covariance matrix, obtaining robust parameter estimates (e.g., factor loadings, intercepts) from the fitted model, and then conducting alignment on these estimates. 

The proposed RAO method will be illustrated on the classic @holzinger1939 dataset modified by @yuan2013, which they added five bad influential observations. 

## OSF Repository

The data analytic scripts and supplemental materials for this project will be available at https://osf.io/c6u32/?view_only=f0073b5f714c43e7becede0714e35447

## Reference
